# cache:
#   directories:
#     - $HOME/.cache/pip
#     - $HOME/.theano
#     - $HOME/miniconda


language: python
python:
    - "2.7"

os:
    - linux

branches:
    only:
    - master
    - dev


# addons:
#   apt:
#     packages:
#       - nvidia-cuda-toolkit
#       - nvidia-cuda-dev
#       - nvidia-profiler

before_install:
    - echo "before_install..."
    - git submodule update --init --recursive
    - git fetch --tags
    - sleep 1
    - git checkout $TRAVIS_BRANCH
    - export PROJECTGITVERSION=`git describe --tags --always |sed 's/^v//'`
    - echo $PROJECTGITVERSION
    - echo $TRAVIS_OS_NAME
    - echo $TRAVIS_COMMIT
    - echo $TRAVIS_TAG
    - export TRAVIS_TAG=`git describe --tags --exact-match HEAD 2>/dev/null`
    - echo $TRAVIS_TAG

    - sudo apt-get -qq update
    # - sudo apt-get install -y cython
    # - sudo apt-get install -y python-numpy
    # - sudo apt-get install -y python-scipy

    - if test ! -e $HOME/miniconda/bin; then
        mkdir -p $HOME/download;
        wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O $HOME/download/miniconda.sh;
        bash $HOME/download/miniconda.sh -b -p $HOME/miniconda;
      fi
    - export PATH="$HOME/miniconda/bin:$PATH"
    - conda update --yes conda
    - conda info -a
    # - conda config --add channels conda-forge

install:
    - echo "install..."
    # - pip install cython
    # - pip install -q numpy cython
    # - pip install numpy
    # - pip install scipy
    # - conda install --yes cython=0.26.1 libffi=3.2.1 libgcc-ng=7.2.0 libstdcxx-ng=7.2.0 numpy=1.12.1 scipy=0.19.1 libgpuarray=0.6.2 pygpu=0.6.2 mako=1.0.6 theano=0.9.0
    - conda install --yes cython=0.26.1 libffi=3.2.1 libgcc-ng=7.2.0 libstdcxx-ng=7.2.0 numpy=1.12.1 scipy=0.19.1 mako=1.0.6 theano=0.9.0
    - conda info -a

script:
    - make test
