cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/miniconda
    # - $HOME/.theano


language: python
python:
    - "2.7"

os:
    - linux

branches:
    only:
    - master
    - dev

before_install:
    - echo "before_install..."
    - git submodule update --init --recursive
    - git fetch --tags
    - sleep 1
    - git checkout $TRAVIS_BRANCH
    - export PROJECTGITVERSION=`git describe --tags --always |sed 's/^v//'`
    - echo $PROJECTGITVERSION
    - echo $TRAVIS_OS_NAME
    - echo $TRAVIS_COMMIT
    - echo $TRAVIS_TAG
    - export TRAVIS_TAG=`git describe --tags --exact-match HEAD 2>/dev/null`
    - echo $TRAVIS_TAG
    - echo "TRAVIS=$TRAVIS"
    - echo "CI=$CI"

    - sudo apt-get -qq update

    - if [ ! -d $HOME/miniconda/bin ] ; then
        echo "Install Miniconda";
        mkdir -p $HOME/download;
        wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O $HOME/download/miniconda.sh;
        bash $HOME/download/miniconda.sh -u -b -p $HOME/miniconda;
      fi
    - export PATH="$HOME/miniconda/bin:$PATH"
    - conda update --yes conda
    - conda info -a

install:
    - echo "install..."
    - pip install codecov
    - pip install codacy-coverage
    - pip install defusedxml
    - pip install bandmat
    - conda install --yes cython=0.26.1 libffi=3.2.1 libgcc-ng=7.2.0 libstdcxx-ng=7.2.0 numpy=1.12.1 scipy=0.19.1 mako=1.0.6 theano=0.9.0 # TODO Really need mako ?
    - conda install --yes matplotlib=2.0.2 # Has to be done separately otherwise conda crashes
    - conda info -a

script:
    - cd percival-tts
    - make
    - tar xvf tests/slt_arctic_merlin_test.tar.gz -C tests/
    - coverage run --source=. --omit="tests/*","external/*" tests/test_base.py
    - coverage run -a --source=. --omit="tests/*","external/*" tests/test_smoke.py
    - bash setenv_travis.sh coverage run -a --source=. --omit="tests/*","external/*" tests/test_smoke_theano.py
    - bash setenv_travis.sh coverage run -a --source=. --omit="tests/*","external/*" tests/test_run.py

after_success:
    - codecov
    - coverage xml
    - export CODACY_PROJECT_TOKEN=4bb1b6ba55634fc1a149c93c939b2242
    - python-codacy-coverage -r coverage.xml
